# Generated by Django 5.2.4 on 2026-02-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ig_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
