# Generated by Django 5.2.4 on 2026-02-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
