# Generated by Django 5.2.4 on 2026-02-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_seat_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='paid',
        ),
        migrations.AddField(
            model_name='booking',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
