# Generated by Django 5.2.4 on 2026-02-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_seat_paid_booking_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
